-- MySQL Script generated by MySQL Workbench
-- Sat 13 May 2017 13:15:43 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog_ecrivain` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `blog_ecrivain` ;

-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_ecrivain`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NULL,
  `p_date` DATETIME NULL,
  `content` VARCHAR(45) NULL,
  `publish` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_ecrivain`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `salt` VARCHAR(23) NULL,
  `role` VARCHAR(50) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_ecrivain`.`media` (
  `id_media` INT NOT NULL AUTO_INCREMENT COMMENT '\n',
  `file_name` VARCHAR(255) NULL,
  `url_file` VARCHAR(255) NULL,
  `post_id` INT NULL,
  PRIMARY KEY (`id_media`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_ecrivain`.`comments` (
  `id_comment` INT NOT NULL AUTO_INCREMENT COMMENT '\n		',
  `date_comment` DATETIME NULL,
  `content` VARCHAR(1000) NULL,
  `report` INT NULL COMMENT '	',
  `read` INT NULL,
  `post_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_comment`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `mydb`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_ecrivain`.`answers` (
  `id_answer` INT NOT NULL AUTO_INCREMENT,
  `date_answer` DATETIME NULL,
  `content` VARCHAR(2000) NULL,
  `report` INT NULL,
  `read` INT NULL,
  `comment_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id_answer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
